# Generated by Django 4.2.3 on 2023-08-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='lon',
            new_name='longitude',
        ),
    ]
