# Generated by Django 4.2.3 on 2023-08-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_lat_coordinates_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
