# Generated by Django 4.2.3 on 2024-04-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='handle',
        ),
    ]
