# Generated by Django 4.2.3 on 2024-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_avatar_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.jpg', upload_to='avatars/'),
        ),
    ]
