# Generated by Django 4.2.3 on 2024-03-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worldKey', models.CharField(max_length=255, unique=True)),
                ('dataFile', models.FileField(upload_to='worlddata/')),
            ],
        ),
    ]
