# Generated by Django 4.2.3 on 2024-02-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_alter_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
